[build]
builder = "RAILPACK"
buildCommand = "php artisan optimize:clear && php artisan filament:assets --ansi && php artisan view:cache"

[deploy]
preDeployCommand = "php artisan optimize:clear && php artisan filament:assets --ansi && php artisan migrate --force --seed && php artisan config:cache && php artisan route:cache && php artisan view:cache"
healthcheckPath = "/up"
healthcheckTimeout = 300
